SELECT LENGTH(SYSDATE) FROM dual;
SELECT * FROM countries;
SELECT ADD_MONTHS('05/JUN/19',3) FROM dual; 
SELECT NEXT_DAY('20-NOV-20', 'WED') FROM dual; 


SELECT TO_CHAR(18, '99999') FROM dual;
SELECT TO_CHAR(18, '099999') FROM dual;
SELECT TO_CHAR(18.35, '099999.999') FROM dual;
SELECT TO_CHAR(18.35, '099999D999' ) FROM dual;
SELECT TO_CHAR(12345678, '99,999,999') FROM dual;
SELECT TO_CHAR(12345678, '99G999G999') FROM dual;
SELECT TO_CHAR(18, '$0999') FROM dual;
SELECT TO_CHAR(18, 'L0999') FROM dual;
SELECT TO_CHAR(-18,'999MI') FROM dual;
SELECT TO_CHAR(-18,'0999PR') FROM dual;
SELECT TO_CHAR(18, 'S0999') FROM dual;

SELECT first_name, salary*1.11111111,
TO_CHAR(salary*1.11111111, '$999,999.99'),
TO_CHAR(salary*1.11111111, '$9,999.99')
FROM employees;

SELECT TO_CHAR('23-SEP-83') FROM dual;

SELECT TO_CHAR(SYSDATE, 'Y') FROM dual;
SELECT TO_CHAR(SYSDATE, 'YY') FROM dual;
SELECT TO_CHAR(SYSDATE, 'YYY') FROM dual;
SELECT TO_CHAR(SYSDATE, 'YYYY') FROM dual;
SELECT TO_CHAR(SYSDATE, 'RR') FROM dual;
SELECT TO_CHAR(SYSDATE, 'YEAR') FROM dual;`
SELECT TO_CHAR(SYSDATE, 'MM') FROM dual;
SELECT TO_CHAR(SYSDATE, 'MON') FROM dual;
SELECT TO_CHAR(SYSDATE, 'MONTH') FROM dual;

SELECT hire_date, TO_CHAR(hire_date, 'Month') FROM employees;
SELECT hire_date, TO_CHAR(hire_date, 'Month', 'NLS_DATE_LANGUAGE = RUSSIAN') || ' Привет!' FROM employees;
SELECT first_name,hire_date FROM employees
WHERE TO_CHAR(hire_date, 'fmMonth') = 'August';

SELECT TO_CHAR(SYSDATE, 'd') FROM dual;
SELECT TO_CHAR(SYSDATE, 'dD') FROM dual;
SELECT TO_CHAR(SYSDATE, 'DDD') FROM dual;
SELECT TO_CHAR(SYSDATE, 'Dy') FROM dual;
SELECT TO_CHAR(SYSDATE, 'Day') FROM dual;
SELECT TO_CHAR(SYSDATE, 'W') FROM dual;`
SELECT TO_CHAR(SYSDATE, 'WW') FROM dual;
SELECT TO_CHAR(SYSDATE, 'q') FROM dual;
SELECT TO_CHAR(SYSDATE, 'CC') FROM dual;

SELECT TO_CHAR(SYSDATE, 'P.M.') FROM dual;
SELECT TO_CHAR(SYSDATE, 'HH24') FROM dual;
SELECT TO_CHAR(SYSDATE, 'MI') FROM dual;
SELECT TO_CHAR(SYSDATE, 'SS') FROM dual;
SELECT TO_CHAR(SYSDATE, 'SSSSS') FROM dual;
SELECT TO_CHAR(SYSDATE, 'fmDAY!Mon?yyyy') FROM dual;
SELECT TO_CHAR(SYSDATE, '"quarter "Q" of "year') FROM dual;
SELECT TO_CHAR(SYSDATE, 'DDth" of "mm') FROM dual;
SELECT TO_CHAR(SYSDATE, 'yyyySP mmSP sssssSP') FROM dual;
SELECT TO_CHAR(SYSDATE, 'MIthSP') FROM dual;


SELECT 'my colleague with ID = '||employee_id || ' and job_id = ' || job_id ||
' joined us on ' || TO_CHAR(hire_date, 'fmDay "the "ddTH "of "fmMonth YYYY')
FROM employees;


